debug: true
validation: false
validThreshold: 8

# Changes walk speed while playing an emote. Set it to true if you don't want players to run around while playing emotes.
# 0.2 is normal walking speed, 0.1 is sneaking speed, 0 to completely disable moving while using emotes.
# It's recommended to also disable jumping, but it's optional and you can enable it if you want to.
slownessWhilePlaying:
  enabled: false
  disableJumping: false
  speed: 0.1